theme: jekyll-theme-hacker
title: Hamza's random blogposts
description: >- # this means to ignore newlines until "baseurl:"
  Blogposts for future reference
github: https://github.com/hamz-a
twitter: https://twitter.com/_bhamza
